# Generated by Django 4.1.7 on 2023-03-03 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='部门名称')),
                ('area', models.CharField(max_length=64, verbose_name='所属区域')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('category', models.SmallIntegerField(choices=[(1, '原辅料'), (2, '包装材料'), (3, '半成品'), (4, '产成品'), (5, '外购商品'), (6, '办公用品'), (7, '设备')], verbose_name='类别')),
                ('model', models.CharField(blank=True, max_length=64, null=True, verbose_name='型号')),
                ('unit', models.CharField(max_length=64, verbose_name='计量单位')),
                ('guarantee_period', models.IntegerField(verbose_name='保质期')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('address', models.CharField(max_length=64, verbose_name='地址')),
                ('phone', models.CharField(max_length=32, verbose_name='电话')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('create_time', models.DateField(verbose_name='入职时间')),
                ('quit_time', models.DateField(blank=True, null=True, verbose_name='离职时间')),
                ('depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.department', verbose_name='部门')),
            ],
        ),
        migrations.CreateModel(
            name='Warehousing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehousing_date', models.DateField(blank=True, null=True, verbose_name='入库时间')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额')),
                ('approved', models.SmallIntegerField(choices=[(0, '未审核'), (1, '已审核')], verbose_name='审核')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.user', verbose_name='操作员')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.supplier', verbose_name='供应商')),
                ('warehousing_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.material', verbose_name='名称')),
            ],
        ),
        migrations.CreateModel(
            name='outbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('outbound', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='出库数量')),
                ('issueAmount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='出库金额')),
                ('issueUnitPrice', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='出库单价')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.department', verbose_name='领取部门')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.material', verbose_name='名称')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.user', verbose_name='操作员')),
            ],
        ),
        migrations.CreateModel(
            name='issueUnitPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('issueUnitPrice', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='出库单价')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.material', verbose_name='名称')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventoryDate', models.DateField(verbose_name='盘点日期')),
                ('inventoryQuantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='盘点数量')),
                ('bookQuantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='账面数量')),
                ('bookAmount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='账面金额')),
                ('errorsNumber', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='误差数量')),
                ('errorsAmount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='误差金额')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.material', verbose_name='名称')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.user', verbose_name='操作员')),
            ],
        ),
    ]
