# Generated by Django 4.1.7 on 2023-03-10 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_alter_outbound_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbound',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.material', verbose_name='名称'),
        ),
    ]
