# Generated by Django 4.1.5 on 2023-03-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_outbound_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='issueUnitPrice',
        ),
    ]
