# Generated by Django 4.1.7 on 2023-03-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_delete_issueunitprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='approved',
            field=models.SmallIntegerField(choices=[(0, '未审核'), (1, '已审核')], default=0, verbose_name='审核'),
            preserve_default=False,
        ),
    ]
