# Generated by Django 4.1.7 on 2023-03-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_inventory_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbound',
            name='batchCode',
            field=models.CharField(default='', max_length=32, verbose_name='批次编码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehousing',
            name='batchCode',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='批次编码'),
        ),
        migrations.AddField(
            model_name='warehousing',
            name='produceDate',
            field=models.DateField(blank=True, null=True, verbose_name='生产日期'),
        ),
        migrations.AddField(
            model_name='warehousing',
            name='surplus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='剩余数量'),
            preserve_default=False,
        ),
    ]
